# Generated by Django 5.2.15 on 2026-07-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Applied'), ('UR ', 'Under Review'), ('S', 'Shortlisted'), ('R', 'Rejected'), ('H', 'Hired')], default='Applied', max_length=5),
        ),
    ]
