# Generated by Django 5.2.15 on 2026-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
