# Generated by Django 5.2.15 on 2026-09-20 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_resume'),
        ('jobs', '0014_coverlettergeneration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Applied'), ('UR', 'Under Review'), ('S', 'Shortlisted'), ('R', 'Rejected'), ('H', 'Hired')], default='A', max_length=5),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_user_job_application'),
        ),
    ]
