# Generated by Django 5.2.15 on 2026-07-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
