# Generated by Django 5.2.15 on 2026-08-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Separate skills using commas'),
        ),
    ]
