# Generated by Django 5.2.15 on 2026-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_job_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
