# Generated by Django 5.2.15 on 2026-09-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='intelligence',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
