# Generated by Django 5.2.15 on 2026-09-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_intelligence'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_found', models.PositiveIntegerField(default=0)),
                ('jobs_imported', models.PositiveIntegerField(default=0)),
                ('jobs_skipped', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
            ],
        ),
    ]
