# Generated by Django 5.2.15 on 2026-09-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobfetchrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfetchrun',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
