# Generated by Django 5.2.15 on 2026-09-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.AddField(
            model_name='job',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
