# Generated by Django 5.2.15 on 2026-09-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_job_created_at_job_imported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fetch_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobfetchrun'),
        ),
    ]
