# Generated by Django 5.2.15 on 2026-09-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_notification_unique_user_job_notification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('source', 'external_job_id'), name='unique_source_external_job'),
        ),
    ]
