# Generated by Django 5.2.15 on 2026-06-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='Unknown Company', max_length=100),
            preserve_default=False,
        ),
    ]
