# Generated by Django 5.2.15 on 2026-07-03 17:48

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_job_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=builtins.id, to='accounts.company'),
            preserve_default=False,
        ),
    ]
