# Generated by Django 5.2.15 on 2026-08-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
