# Generated by Django 5.2.15 on 2026-09-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_candidateprofile_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_job_type',
            field=models.CharField(blank=True, choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('IN', 'Internship')], max_length=2),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_locations',
            field=models.TextField(blank=True, help_text='Separate preferred locations using commas'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_roles',
            field=models.TextField(blank=True, help_text='Separate preferred job roles using commas'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'Onsite')], max_length=20),
        ),
    ]
